### ISSUE TITLE
Rollup --watch broken with @rollup/plugins-typescript 

### ISSUE THREAD

**Issue by MingweiSamuel** [darionco/rollup-plugin-web-worker-loader#57]
This is the same as #38 but the issue is not fixed.

When `rollup-plugin-web-worker-loader` is combined with `@rollup/plugins-typescript` files no longer update after the first build when in `--watch` mode.

Workaround is to use `rollup-plugin-typescript2` instead of `@rollup/plugins-typescript`
See: https://github.com/darionco/rollup-plugin-web-worker-loader/issues/38#issuecomment-727732097

Here is my minimal repro: https://github.com/MingweiSamuel/rollup-typescript-webworkers

**Comment by MingweiSamuel** [comment]
pr https://github.com/darionco/rollup-plugin-web-worker-loader/pull/58 so people can figure out what the heck is going on faster

**Comment by hughrawlinson** [comment]
It looks like the issue in `@rollup/plugins-typescript` is [maybe fixed now](https://github.com/rollup/plugins/issues/957) - is it worth trying it again and seeing if using it is fine now?

**Comment by MingweiSamuel** [comment]
Updated the repro to latest @rollup/plugins-typescript, bug is still there

(I ended up not using `rollup-plugin-web-worker-loader` for my project and instead made a separate rollup config for the worker's javascript bundle)
